import type { AgeCategory } from './types'

export const AGE_CATEGORIES: AgeCategory[] = [
  {
    id: 'a02',
    label: 'Bábätká',
    range: '0–2 roky',
    emoji: '🍼',
    color: '#ff6b9d',
    blurb: 'Hodnoty sú tu skôr pre rodiča než pre dieťa — buduje sa základná dôvera vo svet.',
    values: [
      'Bezpečie a teplo',
      'Dôvera v lásku mamy a otca',
      'Pokojný spánok',
      'Rytmus a rutina',
      'Blízkosť a dotyk',
      'Prvý úsmev, prvé slová a zvuky',
      'Radosť z maličkostí',
      'Pocit „som chcené"',
    ],
    articleIdeas: [
      'Prečo pravidelný rytmus dáva bábätku pocit bezpečia',
      'Ako čítanie a šepkanie buduje dôveru ešte pred prvými slovami',
      'Večerný rituál, ktorý funguje od narodenia',
      'Dotyk ako prvá reč lásky',
    ],
  },
  {
    id: 'a24',
    label: 'Batoľatá',
    range: '2–4 roky',
    emoji: '🧸',
    color: '#ffb347',
    blurb: 'Objavuje sa „ja" — vlastná vôľa, prvé emócie, prvé hranice.',
    values: [
      'Odvaha skúšať nové',
      'Zvedavosť',
      'Pomenovanie emócií („som nahnevaný", „som smutný")',
      'Plakať je v poriadku',
      'Zdravé hranice — sila slova „nie"',
      'Zdieľanie s kamarátom',
      'Prvé priateľstvá',
      'Prvá zodpovednosť (uprac si hračku)',
      'Radosť z objatia',
      'Trpezlivosť počkať chvíľku',
    ],
    articleIdeas: [
      'Ako pomôcť dieťaťu pomenovať, čo cíti (namiesto „neplač")',
      'Záchvaty vzdoru: čo sa naozaj deje v hlave batoľaťa',
      'Prečo je „nie" zdravý krok k samostatnosti',
      'Učíme deliť sa — bez nátlaku',
    ],
  },
  {
    id: 'a47',
    label: 'Predškoláci',
    range: '4–7 rokov',
    emoji: '🦊',
    color: '#9be59b',
    blurb: 'Chápe pravidlá, vzťahy a fér správanie. Veľmi citlivé na spravodlivosť.',
    values: [
      'Čestnosť a pravda',
      'Empatia — vnímať, ako sa cíti druhý',
      'Trpezlivosť',
      'Priateľstvo',
      'Zodpovednosť za svoje veci',
      'Pracovitosť a dotiahnuť vec do konca',
      'Úcta k starším',
      'Ospravedlnenie — „prepáč" niečo znamená',
      'Pomoc v domácnosti',
      'Zdieľanie radosti',
      'Starostlivosť o prírodu a zvieratá',
      'Hrdosť na seba (zvládol som to sám)',
    ],
    articleIdeas: [
      'Prečo deti v tomto veku „klamú" a ako učiť pravdovravnosť bez strachu',
      'Ako naučiť dieťa povedať úprimné „prepáč"',
      'Domáce mikro-povinnosti, ktoré budujú zodpovednosť',
      'Empatia sa dá učiť: jednoduché hry a otázky',
      'Keď dieťa prehráva v hre — fér play od mala',
    ],
  },
  {
    id: 'a710',
    label: 'Mladší školáci',
    range: '7–10 rokov',
    emoji: '🗝️',
    color: '#7cc6ff',
    blurb: 'Svet sa rozširuje o školu, tím a kamarátov. Učí sa zvládať vlastné chyby a porovnávanie.',
    values: [
      'Odvaha povedať pravdu (aj keď je to nepríjemné)',
      'Vytrvalosť — nevzdať to po prvom neúspechu',
      'Spolupráca a fair play v tíme',
      'Riešenie konfliktov slovami, nie silou',
      'Sebadisciplína (úlohy, čas)',
      'Hodnota odlišnosti — každý je iný a to je dobré',
      'Vďačnosť',
      'Zodpovednosť za svoje činy a ich následky',
      'Závisť vs. úprimná radosť z úspechu druhého',
      'Prvé sklamania a ako ich uniesť',
      'Dôvera v rodičov ako bezpečný prístav',
    ],
    articleIdeas: [
      'Ako učiť dieťa zvládať prehru a chybu (chyba = krok vpred)',
      'Keď dieťa žiarli na kamaráta — rozhovor namiesto kárania',
      'Vytrvalosť: pomôžte dieťaťu nevzdať to',
      'Prvé veľké sklamanie a ako pri ňom byť',
      'Vďačnosť ako večerný rituál (3 veci, čo sa dnes podarili)',
    ],
  },
  {
    id: 'a1013',
    label: 'Starší školáci',
    range: '10–13 rokov',
    emoji: '🌌',
    color: '#c89bff',
    blurb: 'Hľadá identitu, vyrovnáva sa s tlakom rovesníkov a prvými hlbšími emóciami.',
    values: [
      'Identita — „kto vlastne som"',
      'Dôvera v seba a vlastný úsudok',
      'Zodpovednosť za vlastné rozhodnutia',
      'Hlboká empatia',
      'Priateľstvo vs. tlak skupiny (vedieť ísť proti prúdu)',
      'Odvaha byť iný',
      'Chyby = učenie, nie zlyhanie',
      'Duševné zdravie a starostlivosť o seba',
      'Prvá láska a prvá strata',
      'Rešpekt k hraniciam — svojim aj cudzím',
      'Hodnota mlčania a vnútorného pokoja',
      'Odvaha požiadať o pomoc',
      'Viera v lepší zajtrajšok',
      'Práca s hnevom a frustráciou',
    ],
    articleIdeas: [
      'Ako hovoriť s preteenom o duševnom zdraví, aby sa neuzavrel',
      'Tlak partie: ako posilniť dieťa, aby vedelo povedať „nie"',
      'Prvá zaľúbenosť a prvá strata — ako byť oporou',
      '„Kto som?" — sprevádzanie pri hľadaní identity',
      'Keď dieťa prestane rozprávať: ako udržať dvere otvorené',
      'Sociálne siete, porovnávanie a sebahodnota',
    ],
  },
]

export const VALUES_HIGHLIGHT = [
  { icon: '💛', bg: '#ffe1ec', title: 'Dôvera v seba', desc: 'Dieťa sa učí, že je v poriadku báť sa — a že odvaha rastie krôčik po krôčiku.' },
  { icon: '🌳', bg: '#fff1c8', title: 'Úcta k starším', desc: 'Babičky, dedovia a múdri stromy — niekedy najlepšie rady prichádzajú z dávnych čias.' },
  { icon: '🫂', bg: '#d5ecff', title: 'Dôvera v rodinu', desc: 'Mamka a ocko sú prístav, kam sa vždy dá vrátiť. Aj keď je svet veľký a hlučný.' },
  { icon: '🌱', bg: '#e5ffd5', title: 'Rast a fantázia', desc: 'Slová roztvárajú svety. Rozprávky pred spaním kŕmia predstavivosť na celý život.' },
]
