import type { AgeCategory } from './types'

export const AGE_CATEGORIES: AgeCategory[] = [
  {
    id: 'a02',
    label: 'Bábätká',
    range: '0–2 roky',
    emoji: '🍼',
    color: '#ff6b9d',
    blurb: 'Krátke uspávanky s opakujúcimi sa slovami a rytmom. Mama alebo ocko ich číta pokojným hlasom.',
    values: [
      'Pokojný spánok',
      'Dôvera v lásku mamy',
      'Bezpečie a teplo',
      'Rytmus a rutina',
      'Prvé slová a zvuky',
      'Blízkosť a dotyk',
      'Radosť z maličkostí',
      'Prvý úsmev',
    ],
  },
  {
    id: 'a24',
    label: 'Batoľatá',
    range: '2–4 roky',
    emoji: '🧸',
    color: '#ffb347',
    blurb: 'Jednoduché príbehy o zvieratkách a prvých výzvach. Malé strašiská, veľké objatia.',
    values: [
      'Odvaha',
      'Zvedavosť',
      'Zdieľanie s kamarátom',
      'Pomenovanie emócií',
      'Prvé priateľstvá',
      'Zdravé hranice — „nie"',
      'Pomoc druhým',
      'Plakať je v poriadku',
      'Radosť z objatia',
      'Prvá zodpovednosť',
    ],
  },
  {
    id: 'a47',
    label: 'Predškoláci',
    range: '4–7 rokov',
    emoji: '🦊',
    color: '#9be59b',
    blurb: 'Prvé hodnoty: priateľstvo, čestnosť, pomoc druhým. Každý príbeh má jasné ponaučenie.',
    values: [
      'Úcta k starším',
      'Čestnosť a pravda',
      'Trpezlivosť',
      'Priateľstvo',
      'Zodpovednosť',
      'Empatia',
      'Pracovitosť',
      'Hrdosť na seba',
      'Ospravedlnenie',
      'Pomoc v domácnosti',
      'Zdieľanie radosti',
      'Starostlivosť o prírodu',
    ],
  },
  {
    id: 'a710',
    label: 'Mladší školáci',
    range: '7–10 rokov',
    emoji: '🗝️',
    color: '#7cc6ff',
    blurb: 'Dobrodružstvá s tajomstvom. Dieťa sa stáva hrdinom vlastnej cesty a učí sa dôverovať.',
    values: [
      'Dôvera v rodičov',
      'Odvaha povedať pravdu',
      'Fair play',
      'Vytrvalosť',
      'Spolupráca v tíme',
      'Riešenie konfliktov',
      'Sebadisciplína',
      'Hodnota odlišnosti',
      'Vďačnosť',
      'Zodpovednosť za činy',
      'Závisť vs. radosť',
      'Prvé sklamania',
    ],
  },
  {
    id: 'a1013',
    label: 'Starší školáci',
    range: '10–13 rokov',
    emoji: '🌌',
    color: '#c89bff',
    blurb: 'Hlbšie témy — strach, strata, prvé veľké rozhodnutia a dôvera v samého seba.',
    values: [
      'Dôvera v seba',
      'Identita a „kto som"',
      'Zodpovednosť za rozhodnutia',
      'Hlboká empatia',
      'Priateľstvo vs. tlak skupiny',
      'Odvaha byť iný',
      'Chyby = učenie',
      'Duševné zdravie',
      'Prvá láska a strata',
      'Rešpekt k hraniciam',
      'Starostlivosť o seba',
      'Hodnota mlčania',
      'Odvaha požiadať o pomoc',
      'Viera v lepší zajtrajšok',
    ],
  },
]

export const VALUES_HIGHLIGHT = [
  { icon: '💛', bg: '#ffe1ec', title: 'Dôvera v seba', desc: 'Dieťa sa učí, že je v poriadku báť sa — a že odvaha rastie krôčik po krôčiku.' },
  { icon: '🌳', bg: '#fff1c8', title: 'Úcta k starším', desc: 'Babičky, dedovia a múdri stromy — niekedy najlepšie rady prichádzajú z dávnych čias.' },
  { icon: '🫂', bg: '#d5ecff', title: 'Dôvera v rodinu', desc: 'Mamka a ocko sú prístav, kam sa vždy dá vrátiť. Aj keď je svet veľký a hlučný.' },
  { icon: '🌱', bg: '#e5ffd5', title: 'Rast a fantázia', desc: 'Slová roztvárajú svety. Rozprávky pred spaním kŕmia predstavivosť na celý život.' },
]
